language: cpp
compiler:
  - gcc

before_script:
  - sudo apt-add-repository -y ppa:czchen/travis-ci
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq cmake
  - sudo apt-get install -yqq ubuntu-sdk

script: "cmake . && make -j4"

notifications:
  irc: "irc.freenode.net#GUIpsp"
